services:

  postgres-auth:
    image: postgres:16
    container_name: dev-auth-db
    environment:
      POSTGRES_DB: dev_auth_db
      POSTGRES_USER: dev_auth_user
      POSTGRES_PASSWORD: turnip
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - dev-irl-network
    restart: unless-stopped

  postgres-auth-test:
    image: postgres:16
    container_name: dev-auth-db-it
    environment:
      POSTGRES_DB: dev_auth_test_db
      POSTGRES_USER: dev_auth_test_user
      POSTGRES_PASSWORD: turnip
    ports:
      - "5434:5432"
    volumes:
      - auth_data_test:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - dev-irl-network
    restart: unless-stopped

volumes:
  auth_data:
  auth_data_test:

networks:
  dev-irl-network:
      name: dev-irl-network
      external: true


