services:
  dev-irl-flyway-migration:
    image: flyway/flyway:latest
    container_name: flyway-migration-dev-irl
    command: migrate
    volumes:
      - ./flyway/flyway.conf:/flyway/conf/flyway.conf
      - ./migrations:/flyway/sql
    networks:
      - dev-irl-network
      
networks:
  dev-irl-network:
      name: dev-irl-network

