
services:
  redpanda:
    image: redpandadata/redpanda:v24.1.9
    command:
      - redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    networks:
      - dev-irl-network

networks:
  dev-irl-network:
      name: dev-irl-network