services:
  redis-local:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - dev-irl-network
    restart: unless-stopped

  redis-test:
    image: redis:latest
    container_name: redis-test-container
    ports:
      - "6380:6379"  # Maps host:container
    networks:
      - dev-irl-network
    restart: unless-stopped

networks:
  dev-irl-network:
    external: true
